installation/checkInstallation.m, solver/optimizeProb.m, solver/setRavenSolver.m
The choice of solver is stored as Matlab preference, which is persistent (no need for saveSolver) and stored in a system dependent location (fixes issues #2).
Additional RAVEN preferences should then also be stored in setpref('RAVEN',...).
=> Set choice of solver as Matlab preference

io/importModel.m
Previously, importModel assumed that _if_ the model is COBRA, the compartment IDs do **not** start with C_, and therefore use the comparment IDs'as is'.
However, if exportModel is used to generate a COBRA model, compartment IDs **are** appended with C_. If one would repeatedly import and export COBRA models, it would repeatedly add C_ in front of the compartment IDs, resulting in something like: C_C_C_m
Now, if the model is COBRA, importModel checks whether the compartment ID starts with C_ and, if true, discards the first two characters.
=> Remove C_ from importModel if model is COBRA

io/importModel.m
Compartment ID of length < 2 called an error after previous pull request.
First attempt to fix this introduced a problem when ID length was 2 or longer, but **not** starting with C_.
Second fix can now deal with comparment IDs like "C_e", "e" and "ext".
Third fix introduces these changes also for compOutside.
(I should probably not push so often...)
=> Small fixes for importModel

core/reporterMetabolites.m
Hi,
I found two little bugs for the "reporterMetabolites" function:
1. The P-Value and Z-score is showing "NA" in the printed result and result file. This happened due to "NA" in the input P-values, that is causing problem during the usage of "mean" and "std" when correcting for background. "mean" and "std" in Matlab doesn't work well with NA.
2. When geneFoldChanges is provided, it showed "Index exceeds matrix dimensions". It is because there's a mismatch between the size of genes, genesPValues and geneFoldChanges, because genes that are not in model.genes are still there in geneFoldChanges.
I tried to provide small fixes, and it works. Let me know your thoughts.
Thanks!!
=> Deal with NA Pvalues and Fold Changes in reporterMetabolites

struct_conversion/ravenCobraWrapper.m
**Problem this branch addreses:**
A bug was introduced in the previous merge of this branch for single genes.
**Case study:**
Loading the yeast consensus model with COBRA and looking at the 7th gene rule (`r_0007`) as a case study, which comes out of COBRA like this:
`x(434)`
* **Expected output - output with this fix:**
`YIL020C`
* **Obtained output in `devel` after the latest merge:**
`x(434`
My apologies for the introduced bug, I checked and all rules of the model are now properly created
=> fix: bug in single genes

core/replaceMets.m
repIdx is not always the first instance in metCompsNidx
=> fix: replaceMets mistakingly removed metabolite

external/metacyc/addSpontaneousRxns.m
In addtion to the retrieved spontaneous reactions, the relevant pathways are now provided as optional output.
=> feat: add option of pathway ids when output spontaneous rxns

io/addJavaPaths.m, io/startup.m
Just as a suggestion for a solution to #75. 
This change will automatically add the java libraries to the dynamic path is the toolbox is on the path. 
It will no longer require a restart of Matlab at first init and the addition will no longer depend on the actual path of the libraries (as they are added dynamically). 
It might also (potentially) solve #55 , if the issue there was that matlabs POI libraries were used instead of the supplied ones.
=> Making Java library addition dynamic

struct_conversion/ravenCobraWrapper.m
See issue #77. pmids are now retrieved from rxnReferences and not rxnNotes when going from COBRA -> RAVEN. They are also stored as `id1; id2 `, not `pmid:id1; pmid:id2 `
=> fix: pmids now in rxnReferences

io/addJavaPaths.m
no need to re-add Java paths that were already added (as this can also throw warnings in certain circumstances)
=> fix: addJavaPaths checks whether paths already added

installation/addRavenToUserPath.m, installation/checkFunctionUniqueness.m
when users has no admin right, it cannot write to `pathdef.m` in matlabroot. Alternatively, this function writes `startup.m` in the userpath, which loads RAVEN to the path every time Matlab is started
=> feat: addRavenToUserPath

io/importModel.m
- fixed bug where names of metMiriams decoded in urn:miriam style were not correctly imported
- remove 'obo.' prefix from metMiriam name identifier
=> fix: importModel metMiriams backwards compatible

core/mergeModels.m, io/exportModel.m, struct_conversion/ravenCobraWrapper.m
- `ravenCobraWrapper` support for more types of metMiriams
- `exportModel` deals with empty (but existing) subSystems field
- `mergeModels` : if the first model does not have metCharges field, it should make a vector of NaN of length(mets) , not a vector of empty cells.
=> fix/exportModel and mergeModel; feat/ravenCobraWrapper

core/getModelFromHomology.m
- in `getModelFromHomology`, to avoid reconstructing a draft model from problematic grRules, standardize grRules of template models early on (issue #120).
=> feat: getModelFromHomology standardize grRules in beginning

core/fillGaps.m, core/getMinNrFluxes.m, solver/optimizeProb.m
Fixes a bug reported on [Gitter](https://gitter.im/SysBioChalmers/RAVEN?at=5b28e67014805602858e44d3), when 'cobra' was set as solver. User confirmed that this fix solved the problem.
- correctly parse empty list of parameters
=> fix: use of 'cobra' as solver

io/exportModel.m, io/importModel.m
Issue #127 
- fix bugs where `importModel` and `exportModel` could not handle models without genes
- prioritized location of gene associations in `importModel`, to work around conflicting/problematic gene assocations in older models (prefefred method is the FBC standard)
=> Fix: misc gene-related import/export of models

external/getBlast.m
- fixed a bug regarding the second problem mentioned in issue #128. That is, `blastStructure` obtained from `getBlast` had incorrect data format for numeric fields (e-value, identity, bitscore, etc.). The incorrect format caused problems when `blastStructure` was used in `getModelFromHomology`.
=> fix: blastStructure format in getBlast

core/convertToIrrev.m
In `convertToIrrev.m`, the field `rxnReferences` was not being extended as the other fields, creating model errors later on with functions such as `removeReactions.m`. This is now fixed.
=> fix: convertToIrrev

io/exportForGit.m
Added a flag (default false) that if true, `exportForGit.m` will error if either RAVEN or COBRA are not on the `master` branch. This is for any repo that wants to ensure that all toolboxes used are on `master` (something that we want in yeast-GEM). The check is done when retrieving the RAVEN/COBRA versions, so to avoid changing the models before performing the check, the version retrieval / eventual master check is now the first thing performed in the function.
=> feat: extra checks in exportForGit

external/kegg/getModelFromKEGG.m
- include a note about the use of the output model in the fillGaps function, to address #146
=> doc: getModelFromKEGG additional note

io/exportModel.m
- fixed an issue for entirely numeric compartment IDs. If that is the case, each compartment ID is preceded with "c_" string. This fix was necessary since OutputSBML did not consider exporting entirely numeric compartment IDs
- added the warning message stating that SBML specification requires the objective function to be set
=> fix: exportModel

io/importModel.m
- if a model is FBCv2 and groups seem to be used, it can still be that they don't specify subsystems. So if none of the assigned group reactions are reactionIDs, then skip trying to assign subsystems from groups.
=> fix: importModel if FBCv2, but groups not used for subsystems

io/exportForGit.m
If RAVEN is not in `master` (where version.txt resides), then it writes the commit id as RAVEN version in the dependencies.txt file
=> feat: exportForGit writes RAVEN commit id if version unavailable

io/exportForGit.m
A recent change in `exportForGit.m` (PR #160) created a bug that duplicated the version number for RAVEN and COBRA (as `fopen` will look up a file in all available paths if full path is not specified):
To correct this, `version.txt` is now opened with its full path. This was tested on yeast-GEM with the changes included locally in the master branch of RAVEN and works as expected:
=> fix: find toolbox version

core/FSEOF.m, core/standardizeGrRules.m
- fix:
- `FSEOF` if model has no subSystems defined or if subSystem field is empty
- style:
- `standardizeGrRules` reports reaction IDs instead of indexex, makes it easier to curate questionable grRules
=> fix: fseof and style:standardizeGrRules

struct_conversion/ravenCobraWrapper.m
Currently, the ravenCobraWrapper requires the comps field to be present in a COBRA model to work.
This field is an optional field in the current data structure and thus not necessarily present in all models.
As a workaround, I modified the function to create the comps field (based on compartmentIDs present in the metabolite names, as is currently standard practice in COBRA models).
=> Adding potenitally missing comps field

external/kegg/getGenesFromKEGG.m, external/kegg/getKEGGModelForOrganism.m, external/kegg/getMetsFromKEGG.m, external/kegg/getModelFromKEGG.m, external/kegg/getPhylDist.m, external/kegg/getRxnsFromKEGG.m
- During model reconstruction from KEGG, the users may download pre-trained HMMs ZIP file, but sometimes MATLAB may fail to extract it. Upon the fix, such error is now correctly reported to the user. This is done by checking existence for _K00844.hmm_ (hexokinase), which is present in all HMM sets
- Misc formatting fixes
=> fix: getKEGGModelForOrganism error report bug

core/addRxns.m, external/kegg/getKEGGModelForOrganism.m
- fix:
- `getKEGGModelForOrganism` order of arguments
- `getKEGGModelForOrganism` can handle full paths to location of KEGG files
- `addRxns` correct format of empty subSystems
Proposed as patch update.
=> fix: addRxns and getKEGGModelForOrganism

external/kegg/getKEGGModelForOrganism.m, tutorial/tutorial4.m
- fix:
- update KEGG reference in tutorial4
- `getKEGGModelForOrganism` correct path to fastaFile
- `getKEGGModelForOrganism` was called in tutorial with incorrect input after fairly recent updates of the function (set the `keepGeneral` parameter)
=> fix: tutorial KEGG

core/constructEquations.m
- fix: get the reversibility information by querying both `lb` and `ub` fields, instead of the obsolete `rev` field that could be inaccurate or unavailable
- doc: refine function description with `Input` and `Output` sub-headings
- feat: additional option is added for allowing the generation of equations with met formulas
**NOTE:** None of these changes affect backward-compatibility of any of the modified functions. All reactions in a model should be organized in their forward direction, typically by setting `ub = 1000` and `lb = -1000 (or 0)`, so that their equations can be correctly constructed by the `constructEquations` function.
=> fix: constructEquations

core/addTransport.m, core/changeGeneAssoc.m, core/changeGrRules.m, core/getModelFromHomology.m, core/removeGenes.m
- fix:
- `removeGenes` doesn't throw an error if gene is not in model
- `getModelFromHomology` works with newer `removeGenes` functionality 
- feat:
- `addTransport` have reaction ID prefix as parameter
- new `changeGrRules` function: in contrast to `changeGeneAssoc`, `changeGrRules` can modify multiple different grRules at the same time. Each function is useful in specific circumstances.
=> fix: removeGenes / feat: addTransport and changeGrRules

io/exportToTabDelimited.m
Fixed bug in `exportToTabDelimited` that would cause error if not all reactions have subsystem information
- fixed minor bug where `exportToTabDelimited` would encounter an error if parsing a model structure with field subSystem containing empty character arrays (e.g. no subSystem assigned/known)
- first encountered when attempting to produce .xlsx file for model via `exportToExcelFormat`.
- updated all documentation
=> fix: exportToTabDelimited bug for subSystems

core/setExchangeBounds.m, core/setMetExchange.m
New function `setMetExchange` allows users to set the exchange flux bounds for a given list of metabolites. This should be helpful for specifying e.g., media conditions, or other nutrient uptake/export fluxes.
=> feat: setExchangeBounds new function to set exchange bounds for given mets

core/setParam.m
- feat:
- 'setParam' can set upper and lower bounds with a defined variability: setting this to `5` results in the lower bound being set at 97.5% of the provided value, and the upper bound at 102.5%. This is inverted for negative bounds.
=> feat: setParam variability bounds

external/kegg/getKEGGModelForOrganism.m, external/kegg/getRxnsFromKEGG.m
- `getRxnsFromKEGG`: increased the number for preallocated reactions as KEGG now includes more than 11k reactions
- `getKEGGModelForOrganism`: fixed several small typos
=> fix: KEGG functions bug + typos

core/addMets.m, core/addRxnsGenesMets.m, core/addTransport.m, core/fillGaps.m, core/getMinNrFluxes.m, core/getModelFromHomology.m, io/exportModel.m, solver/getMILPParams.m, solver/optimizeProb.m
- fix:
- slightly decrease tolerance when using gurobi solver, particularly when solving MILP. If tolerance is set not strict enough, `fillGaps` does not function well.
- `addTransport` when defining new reaction IDs
- error message in `addRxnsGenesMets`
- bug in `getModelFromHomology` when using multiple template models
- bug in `getModelFromHomology` where genes were partial matched: YAL001W is not YAL001W-A
- bug in `fillGaps` where all genes from template models were kept, not only the ones annotated to gap-filling reactions
- `exportModel` replace illegal characters in grRules
- bug in `addTransport` when adding multiple transport reactions
- `addMets`: multiple compartments can be given as either rows or columns
- feat:
- `addTransport` has list of added reaction IDs as alternative …
=> fix: misc gap-filling, addTransport, exportModel, getModelFromHomology bugs

core/getIndexes.m
- Fixed a bug in `getIndexes` where the function would ignore the `returnLogical` input if the `type` input was set to `metscomps`.
=> fix: getIndexes enable returnLogical when "type" is "metscomps"

installation/checkInstallation.m
The hotfix for PR #237: `checkInstallation` is now updated with the new external software directories, somehow forgot to do this during PR #237 
=> fix: checkInstallation according to new external binary directories

core/getElementalBalance.m
Fixed a bug in `getElementalBalance` where if the user supplied reaction indexes, the function would effectively "sort" those indexes in the output without the user knowing.
For example, if I called the function using an input `rxns = [5, 19, 24]`, the results structure would be properly aligned with that index ordering. However, if I called the function using an input `rxns = [24, 5, 19]`, I would get the exact same output, which is not consistent with my input ordering.
This bug was fixed by re-ordering the results based on the ordering of the input indexes prior to returning the output.
=> fix: getElementalBalance

io/importModel.m
- Fix:
- `importModel` parsing of metabolite formula when importing old SBML file (level 2) where formula are in metabolite IDs and not in 'notes' field.
Example of such a model: iAT601 [link](https://biotechnologyforbiofuels.biomedcentral.com/articles/10.1186/s13068-016-0607-x)
=> fix: import of old SBML with formula in metsID

tutorial/tutorial4.m
In `tutorial4`, the more accurate runtime estimates for `getKEGGModelForOrganism` were added for macOS, Unix and Windows systems
=> doc: updated runtime info regarding getKEGGModelForOrganism

installation/checkFunctionUniqueness.m
Added the new feature to `checkFunctionUniqueness`: it now checks for multiple RAVEN versions in MATLAB path and gives a fatal error if it is the case. That is, if at least one quarter of the existing RAVEN functions are found somewhere else in MATLAB path, it is assumed that another RAVEN version exists in MATLAB path.
=> feat: checkFunctionUniqueness now detects multiple RAVEN versions

external/getBlast.m, external/getDiamond.m, external/kegg/getKEGGModelForOrganism.m, external/metacyc/getMetaCycModelForOrganism.m
- Fix:
- Check if query FASTA file is in current directory.
When calling external programs (BLAST, diamond), it's essential that the query (FASTA) files are in the current directory, and not just somewhere in the MATLAB path.
=> fix: check if file exist in current directory

io/exportModel.m, io/importModel.m, struct_conversion/ravenCobraWrapper.m
The `exportModel`, `importModel`, and `ravenCobraWrapper` functions were updated to enable writing and reading of gene, reaction, and metabolite SBO terms to and from an SBML file. This PR addresses Issue #196.
1.  `exportModel` writes SBO terms from `.xyzMiriams` model fields to SBML `.sboTerm` fields.
2.  The default gene SBO term assigned in `exportModel` was changed from `SBO:0000252` ("polypeptide chain") to `SBO:0000243` ("gene"), the latter of which is consistent with [memote](https://memote.readthedocs.io/en/latest/).
3. `importModel` reads SBO terms from the SBML `.sboTerm` fields, and adds them to the corresponding `.xyzMiriams` model fields. 
4. A check was implemented in `importModel` to prevent importing SBO terms if they are all identical for a given entity (e.g., if all …
=> feat: enable I/O of SBO terms from SBML file

core/getElementalBalance.m
The `getElementalBalance` function ignores the order of reactions if they are supplied as a list of reaction IDs, resulting in an output that is not aligned with the inputs.
This same bug was fixed in #240 for inputs of reaction indexes - here I implemented a more general solution that fixes the problem regardless of input type (index numbers, reaction IDs, or logical vector).
=> fix: getElementalBalance ignored order of rxns when using strings (IDs)

core/setExchangeBounds.m
Bug fix in `setExchangeBounds` function.
When using `setExchangeBounds`, if a model contains exchange reactions differing in their direction (i.e., positive flux indicates export for some reactions, but import for others), then the `closeOthers` input should be forced to `false`. The function was not properly making this change, so this has now been corrected.
=> fix: setExchangeBounds fixed bug where closeOthers var was not updated

installation/checkFunctionUniqueness.m, installation/checkInstallation.m
doc/fix:
- `checkInstallation`: divide external binaries into two categories and which are therefore reported separately. The essential binaries (`makeblastdb`, `blastp`, `hmmsearch`) are the ones which are used by most of the users, while the remaining ones (`cd-hit`, `mafft`, `hmmbuild`) are only used if KEGG FTP dump files are parsed in `getKEGGModelForOrganism`. The latter category is therefore not essential.
- `checkInstallation`, `checkFunctionUniqueness`: fix the printed messages to increase the clarity of the printed output
feat:
- `checkInstallation` prints correct RAVEN version (#234)
- `checkInstallation`: enable the external binaries functionality check in Windows (#252)
- `checkInstallation`: add check for `diamond`, which belongs to essential external binaries category, see …
=> doc/feat/fix: enhance checkInstallation

external/metacyc/getMetaCycModelForOrganism.m
- fix bug in `getMetaCycModelOrganism` that output mismatched `genes` and `grRules` fields, by updating `genes` according to the newly generated `rxnGeneMat`
=> fix: correct mismatch between `genes` and `grRules` fields in `getMetaCycModelOrganism`

core/checkTasks.m, core/fitTasks.m
Fixes a bug in the `checkTasks` and `fitTasks` functions.
When parsing metabolite input and output bounds defined in a metabolic task, the `checkTasks` and `fitTasks` functions will overwrite the bounds if a metabolite is listed as both a potential input and output.
For example, say we define a metabolic task for which we know oxygen is involved, but aren't sure whether it will be net produced or consumed (let us assume that, in reality, it needs to be consumed):
IN | IN LB | IN UB | OUT | OUT LB | OUT UB
-- | -- | -- | -- | -- | --
O2[s];glucose[s] |   |   | H2O[s];CO2[s];O2[s] |   |
Since the bounds are not specified, they will default to 0 and 1000 for lower and upper, respectively. Therefore, we would expect the `model.b` field for these metabolites to be:
metabolite | b (lb) | b (ub) …
=> Fix: checkTasks and fitTasks

io/exportModel.m
- fix:
- `exportModel`: if a model has no subSystems field, then the SBML package 'groups' is not required when exporting to SBML. Previously, models without subSystems resulted in invalid SBML files, as they specified that the 'groups' package was used but no groups were specified.
=> fix: exportModel no groups package if no subSystems

struct_conversion/ravenCobraWrapper.m
As mentioned in #286, metabolite KEGG and PubChem IDs are treated differently in the COBRA wrapper, so they should be excluded from the annotation list that adds them as miriams with no changes.
=> fix: add exceptions for met KEGG and PubChem IDs

external/MetaNetX/buildMNXref.m, external/MetaNetX/extractNestedCell.m
- Fix bug in which `buildMNXref.m` failed to output MNXref with the same format as the current MNXref.mat (version 3.0). New function extractNestedCell.m is used for this fix.
- Update MNXref.mat from version 3.0 to version 3.2
=> Fix: update buildMNXref.m and MNXref.mat

struct_conversion/ravenCobraWrapper.m
When converting a model from RAVEN to COBRA, the `grRules` field is kept to _"make things faster, when converting COBRA structure back to RAVEN"_. However, doing this creates conflicts if we edit gene IDs at the COBRA stage, as COBRA doesn't include gene IDs in the rule. For instance, consider the following RAVEN model:
```matlab
>> disp(model_r.grRules{27})
YALI0_A02541g
```
When converted to COBRA, the rule reads:
```matlab
>> model_c = ravenCobraWrapper(model_r);
Converting RAVEN structure to COBRA..
>> disp(model_c.rules{27})
x(5)
```
Hence, we can easily change the id of the gene (without having to touch the rule) by doing:
```matlab
model_c.genes{5} = 'test';
```
As the rule will still point to the 5th position in `genes`. However, if we do that and convert back to RAVEN, the rule …
=> fix: rule conversion in raven-cobra wrapper

core/getModelFromHomology.m
In some cases, multiple genes from the target organism will match with one old gene from the template organism and all of those genes will be included in the template model. If two proteomes from different assemblies of the target organism are used to extract a draft model and we want to compare which proteome extracts the most information from the template model, instead of looking at the new genes, we should look at the number of old genes, since there may be lots of duplications in the new genes.
feat:
- add a feature in `getModelFromHomology.m `to collect both old and new genes
=> feat: collect old and new genes

io/exportForGit.m, io/importModel.m
- feat:
- `exportForGit`: more flexible folder selection with `subDirs` flag to write all files in one folder, or model-specific subfolders.
- fix:
- `importModel`: COBRA `writeCbModel` adds M_ prefix to `modelID`. Unlikely that such prefix is meant to be included in `model.id`, remove this prefix when importing SBML file.
~~Will keep this PR open until https://github.com/MetabolicAtlas/standard-GEM/issues/4 is resolved, to provide the correct model folder name.~~
=> feat: exportForGit folder behaviour & import COBRA modelID

io/writeYaml.m
Following issue https://github.com/SysBioChalmers/yeast-GEM/issues/238, added a `preserveQuotes` flag in `writeYaml.m` that defaults to true to ensure a yaml compatible file. Tested it in [this fork](https://github.com/BenjaSanchez/yeast-GEM/commit/10d7858f80d2b752848fbcc8db7cea347cf237b7) of yeast-GEM and works as intended: All mets/rxns are now stored within quotes, and cobrapy's `load_yaml_model` can properly load the model with no errors.
=> feat: preserveQuotes flag in writeYaml

external/metacyc/getEnzymesFromMetaCyc.m, external/metacyc/getMetaCycModelForOrganism.m, external/metacyc/getMetsFromMetaCyc.m, external/metacyc/getModelFromMetaCyc.m, external/metacyc/getRxnsFromMetaCyc.m
* Add check for the existence of query FASTA file under current path in `getMetaCycModelForOrganism` function
=> fix: add check for query file existence in MetaCyc reconstruction

hpa/parseHPA.m, hpa/parseHPArna.m
Updated `parseHPA` and `parseHPArna` functions for latest version of Human Protein Atlas (HPA), version 19.
The formatting of the protein data did not change, and therefore `parseHPA` only required very minor changes, mostly to comments.
The column names and number of columns for the RNA data is different in version 19. Therefore, the `parseHPArna` function required more changes. The function was also refactored to reduce the amount of repeated code and separate the pieces that actually differ between versions.
=> chore: update parseHPA and parseHPArna

core/simplifyModel.m
* This fix allows also removing boundary compartment from `comps` and `compNames` fields when removing boundary metabolites by `simplifyModel`.
=> fix: remove the boundary compartment when removing boundary mets in `simplifyModel`

core/removeGenes.m
I was inspired by the recent nice work of @IVANDOMENZAIN to further speed up the `removeGenes` function.
The subfunction `canRxnCarryFlux` involved a loop through all model genes, which becomes very slow when checking a model with a lot of reactions and genes. I revised the function to take as input the genes that are present in the grRule being evaluated, so the function only needs to loop through that limited set.
I tested the change with ecHumanGEM to ensure that it returned identical results, and it also decreased the computation time by about 20-fold (690 sec to 36 sec).
=> refactor: further efficiency increase of removeGenes

io/exportModel.m, io/importModel.m
- fix
- `importModel` and `exportModel`, export SBML with http**s** for identifiers.org, keep backwards compatibility to load http links
=> fix: https for identifiers.org

io/exportModel.m
The `exportModel` function will by default add the `InChI=` prefix to entries in the model `inchis` field prior to exporting. If the model's InChI strings already contain this prefix, it will be duplicated in the exported file and cause SBML loading errors.
This PR makes a small modification to the `exportModel` function, which will strip the `InChI=` prefix from InChI strings if it exists, prior to re-adding the prefix. In other words, it will work whether or not a model contains the `InChI=` prefix in the InChI strings.
=> fix: exportModel prevent duplicated InChI prefix

io/exportModel.m
When exporting the chemical formula of a metabolite, the `exportModel` function will only use the `metFormulas` field if the corresponding `inchis` field for that metabolite is missing. According to a comment in the function, the formula is instead retrieved from the `inchis` field if it exists ([lines 322-323 of `exportModel`](https://github.com/SysBioChalmers/RAVEN/blob/0a6efab6a3a7a05d6978c3ad6c4737f530f06f8e/io/exportModel.m#L322-L323)):
```
%Only export formula if there is no InChI. This is because
%the metFormulas field is populated by InChIs if available
```
However, I noticed that when a metabolite does have an `inchis` entry, the formula is never actually extracted from the InChI string. This results in a missing `fbc:chemicalFormula` field for that metabolite in the exported …
=> fix: add chemical formula to metabolites with associated inchi string

io/writeYaml.m, struct_conversion/extractMiriam.m, struct_conversion/ravenCobraWrapper.m
- fix
- `ravenCobraWrapper` parsing `rxnReferences`-field and `pubmed` entries in `rxnMiriams`-field. When converting COBRA -> RAVEN, if `rxnReferences` entry is all numeric, it is assumed to be a PubMed ID and kept in `rxnMiriams`, otherwise `rxnReferences` is kept. For RAVEN -> COBRA, `rxnReferences` and `pubmed` entries from `rxnMiriams` are concatenated. Also use `pubmed` instead of `pmid` as indicating for PubMed IDs. This behaviour is now the same as if the model was directly loaded via RAVEN or COBRA.
- `writeYaml` avoid empty entries.
=> fix: ravenCobraWrapper PubMed ID parsing

core/deleteUnusedGenes.m, core/getModelFromHomology.m
- feat:
- `deleteUnusedGenes` has flag for verbosity 
- fix:
- `getModelFromHomology` keeps reactions with complex grRules if homology was found for at least one of the original genes.
Originally, `getModelFromHomology` was intended to have  this behaviour, where the other (non-homology) genes would then be prefixed with `OLD_`. Later changes on `removeGenes` resulted in too many reactions being deleted. This is now fixed.
Assume the following grRule: `(A and B) or (A and C)`, and only for gene `A` a homolog is found for in the new model: `Anew`
Previous behaviour: the associated reaction will be removed, as gene B and C have no homologs and `(Anew and ... ) or (Anew and ... )` does not have a functional complex.
New behaviour: the associated reaction will be kept, and new grRule is …
=> fix: getModelFromHomology deals with complexes

io/exportModel.m
* This PR modify `exportModel` function to stop adding by prefix `M_` and `R_` to metabolite and reactions ids, as proposed in #353
=> fix: disable adding prefix 'M_' and 'R_' in exprotModel function

io/exportModel.m
tldr; release bugfix version 2.5.2 ASAP, keep changes from #353 for minor release 2.6.0.
1. As Issue [#353](https://github.com/SysBioChalmers/RAVEN/issues/353) fundamentally changes the output from model I/O, it should be part of minor release 2.6.0 (instead of bug-fix 2.5.2), as [mentioned](https://github.com/SysBioChalmers/RAVEN/pull/356#issuecomment-895504529).
2. PR [#356](https://github.com/SysBioChalmers/RAVEN/issues/356) only addressed `exportModel`, without changing `importModel` and `checkModelStruct`, as should be done to completely solve Issue [#353](https://github.com/SysBioChalmers/RAVEN/issues/353).
3. Meanwhile, PR [#358](https://github.com/SysBioChalmers/RAVEN/issues/358) is on standby (waiting for PR [#357](https://github.com/SysBioChalmers/RAVEN/issues/357) to be …
=> Revert "fix: disable adding prefix 'M_' and 'R_' in exprotModel function"

doc/io/exportModel.html, io/exportModel.m
- fix:
- `exportModel` correct handling if a compartment ID is `i` (solves #366)
=> fix: exportModel correct prefix compartment IDs

core/checkModelStruct.m, doc/core/checkModelStruct.html, doc/external/kegg/getKEGGModelForOrganism.html, doc/installation/checkInstallation.html, doc/io/exportModel.html, io/exportModel.m
- feat:
- `checkModelStruct` confirms whether only one objective function is given, otherwise a warning is thrown (SBML L3V1 FBCv2 only allows 1 objective function) (solves #378)
- fix:
- `exportModel` correctly checks for prefixes in model.comps.
=> feat: confirm single obj func by checkModelStruct

core/convertToIrrev.m
- refactor:
- `convertToIrrev` when converting all reactions to irreversible. This reduces running time of `solveLP(model,1)` by ~50% on a yeast model.
=> refactor: convertToIrrev speedup

core/addRxns.m, doc/core/addRxns.html
- fix:
- `addRxns` new subSystems should be cell arrays
=> fix: addRxns new subSystems as cell arrays

doc/installation/checkInstallation.html, doc/io/checkFileExistence.html, installation/checkInstallation.m, io/checkFileExistence.m
- fix
- correctly parse relative paths to model files on Mac/Unix (e.g. by `importModel`)
- feature
- `checkInstallation` checks if a new RAVEN version is available on GitHub, and gives instructions on how to proceed
=> fix: relative paths on mac

installation/checkInstallation.m
- fix:
- `checkInstallation` ensures that binaries (blastp etc.) and MEX files (TranslateSBML etc.) are executable on Mac, as this is not the case if RAVEN is installed as [MATLAB Add-On](https://se.mathworks.com/matlabcentral/fileexchange/112330-raven-toolbox)
=> fix: executable binaries on Mac

installation/checkInstallation.m
bug where `checkInstallation` needs validation on Mac. But `which` function in MATLAB only work if the file exits in the MATLAB path. Then, validation lines are relocated. 
Initial output:
`>> checkInstallation
*** THE RAVEN TOOLBOX ***
> Checking RAVEN release               2.7.8
> You are running the latest RAVEN release
> Checking MATLAB release              2022a
> Checking system architecture         maci64
> Make binaries executable           Error using checkInstallation>makeBinaryExecutable
Failed to make blastp.mac executable: chmod: : No such file or directory
Error in checkInstallation (line 66)
status = makeBinaryExecutable();`
Output after adjust:
`>> checkInstallation
*** THE RAVEN TOOLBOX ***
> Checking RAVEN release               DEVELOPMENT
> Checking MATLAB release …
=> fix: checkInstallation on mac

core/fitTasks.m
- fix bug in `fitTasks` that is failed to do restore field `b` in the end. This is discovered by the issue [#22](https://github.com/SysBioChalmers/Mouse-GEM/issues/22) reported in Mouse-GEM 
=> fix: resume field `b` in fitTasks

installation/checkInstallation.m
- fix bug where `checkInstallation` failed to do function find the path for binaries on Mac
=> fix: binary executable in mac

doc/installation/checkFunctionUniqueness.html, installation/checkFunctionUniqueness.m
- fix:
- `checkFunctionUniqueness` on Mac/Unix with non-RAVEN paths
=> fix: checkFunctionUniqueness on mac/unix

doc/installation/checkInstallation.html, installation/checkInstallation.m
- fix:
- `checkInstallation` find `printOrange` on new RAVEN installations (solves #492)
=> fix: checkInstallation printOrange function

doc/io/readYAMLmodel.html, doc/io/writeYAMLmodel.html, io/readYAMLmodel.m, io/writeYAMLmodel.m
- fix:
- `readYAMLmodel` allows for a model that has gene entries that are not present in any grRules: these are unused genes and should be allowed. This also prevents a bug where gene annotations are wrongly assigned.
- `writeYAMLmodel` correct parsing of text to avoid escape characters (e.g. SMILES may contain `\C`).
=> fix: readYAMLmodel allows non-used genes

.gitignore, core/getAllowedBounds.m
Refactor `waitbar` function used in `getAllowedBounds` to `progressbar`. Note that this is the only function that uses waitbar in RAVEN.
=> refactor: getAllowedBounds to use progressbar

core/addRxnsGenesMets.m, core/standardizeGrRules.m, doc/core/addRxnsGenesMets.html, doc/core/getAllowedBounds.html, doc/core/standardizeGrRules.html, doc/io/readYAMLmodel.html, io/readYAMLmodel.m
- fix:
- `readYAMLmodel` should always make model.c-field, even if no objective function is specified.
- `standardizeGrRules` should throw error if no grRules field is found.
- doc:
- `addRxnsGenesMets` more detailed error message if reactions cannot be found.
=> fix: readYAMLmodel always make c-field

doc/testing/unit_tests/solverTests.html, testing/unit_tests/solverTests.m
- fix:
- `checkInstallation` (via `solverTests`) will not report soplex as `fail` on Windows when using RAVEN-provided binary (solves #513).
=> fix: solverTests for soplex

doc/io/writeYAMLmodel.html, doc/struct_conversion/ravenCobraWrapper.html, io/writeYAMLmodel.m, struct_conversion/ravenCobraWrapper.m
- Fixes:
- `ravenCobraWrapper` properly makes `comps` and `compNames` fields when lacking in COBRA model
- `writeYAMLmodel` can deal with mixture of nested and not-nested cell arrays of subsystems (as COBRA models can have)
=> fix: ravenCobraWrapper variations on cobra fields

doc/struct_conversion/extractMiriam.html, struct_conversion/extractMiriam.m
- Fixes:
- `extractMiriam` should allow cell array of multiple miriamNames as input.
=> fix: extractMiriamallows multiple miriamNames

doc/installation/checkInstallation.html, installation/checkInstallation.m
- Fix:
- `checkInstallation` correctly makes binaries executable on Ubuntu (solves #527)
=> fix: makeBinaryExecutable explicit filenames

doc/installation/checkInstallation.html, installation/checkInstallation.m
- fix:
- `checkInstallation` finding RAVEN when installed as MATLAB Add-On
=> fix: checkInstallation if MATLAB Add-On
