core/addExchangeRxns.m
core/addMets.m
core/addRxns.m
core/addTransport.m
core/changeRxns.m
core/checkModelStruct.m
core/expandModel.m
core/makeSomething.m
core/mergeModels.m
core/permuteModel.m
core/predictLocalization.m
core/removeMets.m
core/removeReactions.m
installation/checkInstallation.m
io/exportToExcelFormat.m
io/importExcelModel.m
solver/optimizeProb.m

1) Small fix in optimiseProb. To get back Mosek LP solver functionality.
2) Several changes in checkInstallation. See the corresponding commit message for more details.
3) Introduced new non-mandatory fields in model structure: rxnNotes,
rxnReferences, confidenceScores and metCharge. See the corresponding commit message for more details.

Simonas branch 1

---

core/removeMets.m

To enable printFluxes functionality

Small fix for removeMets.m

---

README.md
core/makeSomething.m
io/exportToExcelFormat.m

Added download links for pre-trained KO HMMs.

Updated README

---

io/exportModel.m
io/importModel.m
struct_conversion/mosekToCobraProb.m

Including the latest bug fixes into the working branch

Small bugs

---

core/addRxnsGenesMets.m

a string of new grRules can be specified to use for the new reactions

feat: addRxnsGenesMets supports adding new genes

---

.gitignore
core/addRxns.m
core/changeRxns.m
core/getIndexes.m
core/mergeModels.m
core/replaceMets.m
external/metacyc/getRxnsFromMetaCyc.m
io/exportModel.m

fix: various functions

---

core/randomSampling.m

just a handy flag for displaying progress of the random sampling function, as the latter tends to take long

feat: random sampling flag

---

io/exportForGit.m
io/importModel.m

- `importModel` now correctly finds objective function in SBML FBCv2 file
- `exportForGit` makes the required directories only

Fix/importModel and exportForGit

---

.github/issue_template.md
.github/pull_request_template.md

- templates generated for PR and issues

feat: PR and issue templates

---

installation/addRavenToUserPath.m

- bug in `addRavenToUserPath` nargin check fixed (issue #125)

fix: addRavenToUserPath nargin check

---

external/getBlast.m

- bug regarding numeric gene names fixed in `getBlast` (issue #128)

 fix: numeric gene names compatibility with getBlast

---

core/constructEquations.m

- constructEquations was incorrectly retrieving metabolite compartments, but this has now been repaired.

merge fix/constructEquations branch with devel

---

core/constructEquations.m

- fix `constructEquations` bug that was introduced by recent changes in its functionality

fix: constructEquations did not correctly extract stoichiometric coefficients

---

core/addGenesRaven.m
core/addRxns.m
core/addRxnsGenesMets.m

- refactor:
- `addRxnsGenesMets` should tunnel new genes to `addRxns`, which will then tunnel this to `addGenesRaven`, instead of duplicating code
- fix:
- `addRxns` should use the existing model if no new genes were found, even if allowNewGenes flag was true
- `addGenesRaven` should update rxnGeneMat with as many columns as there are new genes

fix: update rxnGeneMat when new genes added

---

README.md

doc: update citation

---

external/getBlastFromExcel.m

Addresses issue #180 
- fix:
- `getBlastFromExcel` Mac compatibility
- `getBlastFromExcel` parses bitscore and ppos values

fix: getBlastFromExcel

---

core/getAllSubGraphs.m

* fix the bug in function `getAllSubGraphs.m` when the number of subGraphs is over 100
* refine function description

fix: getAllSubGraphs

---

external/getBlastFromExcel.m

- fix:
- as spotted by @zhxiaokang (#180)
- style:
- update documentation style with "input" and "output" references

fix: getBlastFromExcel bug

---

core/predictLocalization.m
external/getWoLFScores.m
external/parseScores.m

* doc:
* standardized the definition part and comments for compartalization module functions: `predictLocalization`, `parseScores` and `getWoLFScores`
* feat:
* in `parseScores` and `getWoLFScores` renamed `geneScoreStruct(ure)` to `GSS`, like it is named in `predictLocalization`
* in `getWoLFScores` clarified that this function works only in Linux
* fix:
* fixed an issue in `predictLocalization` when the added transport reactions had their `subSystems` in incorrect format

doc/feat/fix: compartmentalization module

---

README.md

* feat:
* added Zenodo badge, re-arranged badges and updated citation information in README.md

feat: add Zenodo badge

---

external/kegg/getKEGGModelForOrganism.m

- doc
- `getKEGGModelForOrganism` more detailed error message if download of HMM fails (#305)

doc: getKEGGModelForOrganism

---

core/setParam.m

- fix:
- `setParam` when multiple 'obj' values are changed at the same time (solves #350)

fix: setParam multiple obj parameters

---

doc/core/deleteUnusedGenes.html
doc/core/getModelFromHomology.html
doc/core/setParam.html

- doc:
- updated HTML documentation for RAVEN with updateDocumentation function (MATLAB 2020b, Win 10)

chore: update documentation

---

doc/io/exportForGit.html
doc/io/exportModel.html
doc/io/exportToExcelFormat.html
doc/io/getToolboxVersion.html
doc/io/sortIdentifiers.html
doc/io/writeYaml.html
io/exportForGit.m
io/getToolboxVersion.m

This PR fixes #382 .
In accordance to the original issue, this PR should also resolve:

chore: rename master to main

---

.github/issue_template.md
.github/pull_request_template.md
.github/workflows/testing-comment.md
.github/workflows/testing.yml

To simplify development, there should be a way for tests to run automatically. This PR aims to resolve this by adding basic support to run the currently defined tests.
This PR is based on a version of `devel` that has the latest from the main branch, which is why there is long list of commits. I found this to be the easiest way of pulling in the `.github` folder that was needed, which seemed to exist only on the master branch.

feat: automated testing

---

doc/external/kegg/getKEGGModelForOrganism.html
external/kegg/getKEGGModelForOrganism.m

* fix:
* `getKEGGModelForOrganism`: added the check for `organismID` in FASTAless mode

fix: getKEGGModelForOrganism now checks organismID validity

---

.github/workflows/testing.yml

This PR fixes the parsing of the tests result that are run with GH Actions, thus improving the short version of the results that gets posted automatically to the PR thread.

fix: posting results from tests via Actions

---

INIT/runINIT.m
core/changeRxns.m
doc/INIT/runINIT.html
doc/core/changeRxns.html
doc/installation/checkInstallation.html
installation/checkInstallation.m

This PR fixes a bug that was introduced in a [previous "fix"](12706c50b376503ade4a79de3a639f9cdcdcc539) of the `runINIT` function. It should resolve errors in running tINIT including those reported [here](https://github.com/SysBioChalmers/Human-GEM/discussions/395).

fix: resolves bug in runINIT with csense vector

---

core/randomSampling.m
doc/core/randomSampling.html

- doc:
- `randomSampling` more accurate and detailed progress and warning reporting, to prevent confusion as in #438 

doc: randomSampling progress reporting

---

core/expandModel.m
doc/core/expandModel.html

For Human GEM, it used to take 419 s on my computer - now takes 22 s. I tested all fields that exist in Human-GEM, they were identical after calling the old and new version of the function.

opt: Optimized expandModel 

---

.github/workflows/commentsFromTests.md
.github/workflows/tests.yml
README.md
core/findRAVENroot.m
installation/checkInstallation.m

This PR aimed to update the GH Action dependencies and formatting. While doing so, a bug was spotted that highlighted that the latest RAVEN was actually not used, since the GH Action was relying on the system-provided RAVEN.
This PR also adds a corresponding badge in the Readme.

feat: update GH Action workflow

---

doc/installation/checkInstallation.html
doc/io/readYAMLmodel.html
doc/solver/optimizeProb.html
io/readYAMLmodel.m
solver/optimizeProb.m

- fix:
- `optimizeProb` and `readYAMLmodel` on MATLAB <2020b (solves #478).

fix: optimizeProb and readYAMLmodel on MATLAB <2020b.

---

doc/io/importModel.html
io/importModel.m

- fix:
- `importModel` assigns -Inf and Inf if no LB and/or UB values are defined.

fix: importModel with zero LB and UB

---

doc/external/metacyc/getMetaCycModelForOrganism.html
doc/external/metacyc/getMetsFromMetaCyc.html
doc/external/metacyc/getModelFromMetaCyc.html
external/metacyc/getMetaCycModelForOrganism.m

- feat:
- `getMetaCycModelForOrganism` input and output of blastStructure (before cutoffs applied), so that function can repeatedly be run with different cutoffs without having to rerun blast/diamond

feat: getMetaCycModelForOrganism I/O BLAST structure

---

doc/struct_conversion/ravenCobraWrapper.html
struct_conversion/ravenCobraWrapper.m

- fix:
- `ravenCobraWrapper` makes empty model.c if COBRA model had no `c` field (is not necessarily made by readCbModel)

fix: ravenCobraWrapper with no model.c

---

core/FSEOF.m
core/checkRxn.m
core/findGeneDeletions.m
core/runDynamicFBA.m
core/runSimpleOptKnock.m
doc/core/FSEOF.html
doc/core/checkRxn.html
doc/core/findGeneDeletions.html
doc/core/runDynamicFBA.html
doc/core/runSimpleOptKnock.html
doc/installation/checkFunctionUniqueness.html
doc/installation/checkInstallation.html
doc/solver/solveLP.html
doc/testing/unit_tests/fillGapsLargeTests.html
doc/tutorial/tutorial1.html
doc/tutorial/tutorial3_solutions.html
installation/checkInstallation.m
solver/solveLP.m
testing/unit_tests/fillGapsLargeTests.m
tutorial/tutorial1.m
tutorial/tutorial3_solutions.m

- Fixes:
- various changes in relation to `solveLP` swapping the sign of reported objective function (`sol.f`), as already announced in [2.7.12](https://github.com/SysBioChalmers/RAVEN/releases/tag/v2.7.12).
- Features:
- `checkInstallation` reports how RAVEN was installed, as described in the [Wiki](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#obtain-raven-toolbox).

fix: correct sign of sol.f field
